name: Deploy to AWS lightsail

on:
  pull_request:
    branches: ["prod"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS lightsail
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sh ~/skripsi-dockerized/shell-scripts/down.sh
            cd ~/skripsi-dockerized/laravel/
            git checkout prod
            git fetch
            git pull
            sh ~/skripsi-dockerized/shell-scripts/up.sh
