name: Deploy to AWS lightsail

on:
  pull_request:
    branches: ["prod"]
    types: ["closed"]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS lightsail
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/skripsi-dockerized/
            docker compose exec -it php-fpm sh -c "php artisan down --render='errors::upgrade'"
            cd ~/skripsi-dockerized/laravel/
            git checkout prod
            git fetch
            git pull
            cd ~/skripsi-dockerized/
            docker compose exec -it php-fpm sh -c "php artisan up"
